runtime: go111

handlers:
- url: /check
  script: _go_app
  secure: always
  login: admin
- url: /remove
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app
  secure: always
