FROM golang:1.13

ARG PROTO_VERSION=3.6.1

RUN apt-get update && apt-get install -y unzip && \
    mkdir /proto && \
    wget -P /proto https://github.com/protocolbuffers/protobuf/releases/download/v$PROTO_VERSION/protoc-$PROTO_VERSION-linux-x86_64.zip && \
    unzip /proto/protoc-$PROTO_VERSION-linux-x86_64.zip -d /proto && \
    rm -rf /proto/protoc-$PROTO_VERSION-linux-x86_64.zip && \
    go get -u github.com/golang/protobuf/protoc-gen-go
ENV PATH="/proto/bin:${PATH}"

CMD sh -c "protoc --go_out=paths=source_relative:. watchdog.proto && \
    protoc -I=. --python_out=. watchdog.proto && \
    protoc --js_out=import_style=commonjs,binary:. watchdog.proto"
