runtime: go
api_version: go1

handlers:
- url: /check
  script: _go_app
  secure: always
  login: admin
- url: /remove
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app
  secure: always
